# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

install:
- pip install -r requirements.txt
- pip install -r requirements/testing.txt
- pip install -r requirements/documentation.txt
- pip install coveralls

script:
- nose2
- feature_files=(`find ./ -maxdepth 1 -name "*.feature"`); if [ ${#feature_files[@]} -gt 0 ]; then behave ./tests/acceptance/; else echo "Skipping acceptance tests..."; fi;

after_success:
  - coveralls
